dataset:
  name: "german"
  path: "datasets/german_sklearn/german_sklearn.csv"
  path_train: "datasets/german_sklearn/german_sklearn_train.csv"
  path_test: "datasets/german_sklearn/german_sklearn_test.csv"
  target: "class"
  sensitive: "sex"
  privileged: ["male"]        #1
  unprivileged: ["female"]    #0
  favorable: "good"           #1
  unfavorable: "bad"        #0

model:
  - name: "xgboost"
    params:
      n_estimators: 200
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8

  - name: "decision_tree"
    params: {}

  - name: "gaussian_nb"
    params: {}

  - name: "svm"
    params:
     probability: true
     kernel: "linear"
     max_iter: 2000

  - name: "random_florest"
    params: {}

  - name: "logistic_regression"
    params:
      max_iter: 2000

  - name: "neural_network"
    params:
      hidden_layer_sizes: [128, 64]
      activation: "relu"
      solver: "adam"
      alpha: 0.0001
      batch_size: 32
      learning_rate_init: 0.001
      max_iter: 300
      early_stopping: true
      validation_fraction: 0.1
      n_iter_no_change: 10

  - name: "knn"
    params:
      n_neighbors: 3
      weights: "distance"
      algorithm: "auto"
      leaf_size: 30
      p: 2
      metric: "minkowski"

mitigation:
  pre:
    - name: "none"
      params: {}

    - name: "reweighing"
      params: {}

    - name: "disparate_impact_remover"
      params: 
        repair_level: 1.0 # 1.0 = reparação total

  in:
    - name: "none"
      params: {}

    - name: "grid_search"
      params: 
        constraint: "DemographicParity" #EqualizedOdds
        grid_size: 3

    - name: "exponentiated_gradient"
      params: 
        constraint: "DemographicParity" #EqualizedOdds
        eps: 0.01

  post:
    - name: "none"
      params: {}

    - name: "reject_option_classification"
      params: {}

    - name: "equalized_odds_postprocessing"
      params: {}
