dataset:
  name: "adult"
  path: "datasets/adult_sklearn/adult_sklearn.csv"
  path_train: "datasets/adult_sklearn/adult_sklearn_train.csv"
  path_val: "datasets/adult_sklearn/adult_sklearn_val.csv"
  path_test: "datasets/adult_sklearn/adult_sklearn_test.csv"
  cols_exclude: ["fnlwgt"]
  cols_cat: ["workclass","education","marital-status","occupation","relationship","race","native-country"] # colonas categoricas que serão transformada para one-hot 0/1
  target: "income"
  sensitive: "sex"
  privileged: ["Male"]        #1
  unprivileged: ["Female"]    #0
  favorable: ">50K"           #1
  unfavorable: "<=50K"        #0

model:
  - name: "xgboost"
    params:
      objective: "binary:logistic"   # função de perda para classificação binária
      n_estimators: 200              # número de árvores# número de árvores# número de árvores
      max_depth: 6                   # profundidade máxima de cada árvore
      learning_rate: 0.1             # taxa de aprendizado (shrinkage)
      subsample: 0.8                 # fração de amostras por árvore (regularização)
      colsample_bytree: 0.8          # fração de features usadas por árvore

  - name: "decision_tree"
    #params: {}
    params:
      ccp_alpha: 0.0                 # nível de poda (0 = sem poda)
      criterion: gini                
      min_impurity_decrease: 0.0     
      min_samples_leaf: 1            
      min_samples_split: 2           
      min_weight_fraction_leaf: 0.0  
      splitter: best


  - name: "bernoulli_nb"
    params:
      alpha: 1.0          # Suavização de Laplace/Lidstone (quanto maior, mais suaviza). 
      binarize: 0.0       # Limite para transformar valores em binário (se None, não binariza).
      fit_prior: True     # Se deve aprender as probabilidades a priori das classes.
      force_alpha: True   # força uso de alpha mesmo sem priors

  - name: "svm"
    params:
      C: 1.0
      dual: auto
      fit_intercept: True
      intercept_scaling: 1 
      loss: squared_hinge
      max_iter: 1000 
      multi_class: ovr 
      penalty: l2
      tol: 0.0001 

  - name: "random_forest"
    params:
      bootstrap: True
      ccp_alpha: 0.0
      criterion: gini
      max_bins: 256
      max_features: sqrt
      min_bin_size: 1
      min_impurity_decrease: 0.0
      min_samples_leaf: 20
      min_samples_split: 2
      min_weight_fraction_leaf: 0.0
      n_estimators: 100
      oob_score: False  
 
  - name: "logistic_regression"
    params:
      max_iter: 2000
      C: 1.0
      dual: False
      fit_intercept: True 
      intercept_scaling: 1
      multi_class: deprecated
      penalty: l2
      solver: lbfgs
      tol: 0.0001
 
  - name: "neural_network"
    params:
      hidden_layer_sizes: [128, 64]
      activation: "relu"
      solver: "adam"
      alpha: 0.0001
      batch_size: 32
      learning_rate_init: 0.001
      max_iter: 300
      early_stopping: true
      validation_fraction: 0.1
      n_iter_no_change: 10


mitigation:
  pre:
    - name: "none"
      params: {}

    - name: "reweighing"
      params: {}

    - name: "disparate_impact_remover"
      params:
        repair_level: 1.0 # 1.0 =  total repair

    #- name: "optimized_preprocessing"
    #  params: {}

    #- name: "lfr"
    #  params: 
    #    k: 2 # Number of prototypes.
    #    Ax: 0.01  # Input recontruction quality term weight
    #    Ay: 10 # Output prediction error
    #    Az: 0.001      # Fairness constraint term weight
    #    print_interval: 250
    #    maxiter: 3000
    #    maxfun: 3000
    #    threshold: 0.5
    #    verbose: 1

  in:
    - name: "none"
      params: {}

    #- name: "meta_fair_classification"
    #  params: 
    #     type: sr # fdr - false descovery rate e sr (statiscal rate ou disparate impact)
    #     tau: 1 # 0 foca em acurácia, 1 foca em fairness

  post:
    - name: "none"
      params: {}

    - name: "reject_option_classification"
      params: {}

    - name: "equalized_odds_postprocessing"
      params: {}

    #- name: "calibrated_odds_postprocessing"
    #  params:
    #     cost_constraint: "weighted" #"fpr"#"fnr"

    #- name: "deterministic_reranking"
    #  params:
    #    rerank_type: Greedy